Reviewer protocol
ThriveCoin/thc-protocol-sol pull request #20
Opened 2024-12-30 16:55 UTC by matejdrazic

This branch holds the work (smart contracts) built for the "Reviewer protocol". 

A `ThriveReviewFactory` contract handles the creation of `ThriveReview` instances using the `Clones` solidity pattern. It has options to create `ThriveReview and `WorkUnit` in the same transaction, but it can also connect an existing `WorkUnit` to a `ThriveReview` contract.

`ThriveReview` contract should handle all logic reviews-oriented. Right now it (should) have everything implemented except the dispute mechanism.

Currently: writing tests...

2025-01-05 11:56 UTC, vigan-abd requested changes

2025-01-05 11:56 UTC, vigan-abd commented on src/ThriveWorkerUnit.sol
> +    modifier onlyThriveReviewFactory() {
worker units can work without reviewer as well, reviewer is contract is actually validator

2025-01-05 11:56 UTC, vigan-abd commented on src/ThriveWorkerUnit.sol
> +    address public thriveReviewFactory;
worker unit should be agnostic of reviewer

2025-01-05 11:56 UTC, vigan-abd commented on src/ThriveWorkerUnit.sol
> +
see other comments about reviewer not being part of worker unit

2025-01-05 11:56 UTC, vigan-abd commented on src/interface/IThriveWorkerUnitFactory.sol
> +interface IThriveWorkerUnitFactory {
I'm not fully following why we need interfaces for factories? don't they simply create specific worker units?

2025-01-05 11:56 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +        require(submissionCounter < reviewConfiguration.maximumSubmissions, "Maximum amount of submissions has been reached");
hmm afaik users can make submissions and claim rewards more than once, @rilindmehmeti is that right?

2025-01-05 11:56 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +    ) external onlyUserWithBadges(reviewConfiguration.submitterBadges) returns (uint256 submissionId) {
Maybe onlyUserWithBadges could be something like canContribute(address) returns (bool) on WorkerUnit? Currently we're replicating behavior

2025-01-05 11:56 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +    function createSubmission(
currently we're not doing any checks if worker unit contract has enough funds for all pending submissions and maxCompletionsPerUser

2025-01-05 11:56 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +    function _reachDecisionOnSubmission(uint256 submissionId_) internal {
I would suggest to make this virtual so it can be overriden later

2025-01-05 11:56 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +                    IThriveWorkerUnit(workerUnitAddress).confirm(submission.contributor, submission.submissionMetadata);
this sends funds to contributor and reward to ThriveReview, were do we distribute funds to reviewers?

2025-01-05 11:56 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +                submission.decision = Decision.REJECTED;
we're not distributing user's reserved funds to reviewers

2025-01-05 11:56 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +    }
I'm not following this fully, reviewers always confirm the contribution with worker unit and then handle received reward as validator in case of Accepted, and in case of rejected they don't call confirm but claim user's reserved funds on review contract, shouldn't _reachDecisionOnSubmission be enough to deal with this?

2025-01-05 11:56 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +    function claimReviewerReward(uint256 reviewId_) public {
not sure but this can be done automatically during consensus on submission

2025-01-05 11:56 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +    function retrieveFunds() external onlyOwner {
why is this needed? contract deals with distributing funds, owner shouldn't be able to take them afaik

2025-01-05 11:56 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +    function createSubmission(
we're not reserving funds from user in this case, we should get value that is equivalent of worker unit reward for validator

2025-01-05 12:02 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +    function retrieveFunds() external onlyOwner {
sorry missed slack comments, but still I'm not sure what owner can claim here? I understand that there could be some pending reviews that weren't completed and users have locked funds, but shouldn't we return these back to users?

2025-01-05 14:10 UTC, matejdrazic commented on src/ThriveWorkerUnit.sol
> +
Understood. WorkerUnit should be agnostic of reviewers protocol so this should be deleted.

This was developed as part of a feature where a review can be connected to a work unit that was made previously in time (as discussed with Rilind). But that feature was noted as "nice-to-have" so we can just scrape it. 

Makes sense.

2025-01-05 14:24 UTC, matejdrazic commented on src/interface/IThriveWorkerUnitFactory.sol
> +interface IThriveWorkerUnitFactory {
They certainly do - but better to have an interface to connect to it rather than importing the entire factory - which may increase over time as features are added.

2025-01-05 14:26 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +        require(submissionCounter < reviewConfiguration.maximumSubmissions, "Maximum amount of submissions has been reached");
Pasting my convo with @rilindmehmeti:
Matej Drazic-Balov
  12:32 PM
hey Rilind, one question about some requirements we talked about is that a user should have a limited amount of submissions and he should not have more than one pending at a time? My question is should he be allowed to submit again only if his first submission was rejected or can he have more than one accepted submission? First one makes more sense but just wanted to make sure.

Rilind Mehmeti
  12:39 PM
He should only have one accepted submission

2025-01-05 14:33 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +    ) external onlyUserWithBadges(reviewConfiguration.submitterBadges) returns (uint256 submissionId) {
Sure - but I felt like its better to have it all in one place - the Review contract - because other badge validations are done on the Review (reviewing, judging).

But if you see some benefit of doing it only on WorkerUnit (for submissions) - definitely!

2025-01-05 14:52 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +    function createSubmission(
That check is done on WorkerUnit::initialize() right? 

You would want to check on `createSubmission()` if there are funds on WorkerUnit to pay out that submission in case it gets ACCEPTED?

2025-01-05 15:09 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +    function createSubmission(
Does it make sense to dynamically check for every submission if it has funds on `WorkerUnit` for pay out? 

Funds for paying out completions are secured on `WorkerUnit::initialize()` so we know beforehand how many submissions are allowed - and that is what I thought would be stored in reviewConfig.maxSubmissions

2025-01-05 15:16 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +                submission.decision = Decision.REJECTED;
Firstly, what do you mean by "user's reserved funds" ?

Secondly, at first we imagined the reviewers should manually claim their rewards by calling `claimReviewerReward` function because of security patterns. Distributing funds to multiple addresses can result in failing/blocked distribution for all participants involved.

please see this: https://www.vibraniumaudits.com/post/understanding-the-receive-and-fallback-functions-in-solidity

2025-01-05 15:21 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +    }
I do not understand what do you mean by "user's reserved funds on review contract". Where are users suppose to reserve their funds?

But to answer your question, this function should serve to finalize a submission when a threshold agreement can not be reached with reviews. By finalizing submissions we allow the correct reviewers to withdraw their funds.

2025-01-05 15:24 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +    function claimReviewerReward(uint256 reviewId_) public {
You mean the rewards distribution?

Yes it could but it raises some security concerns (as mentioned in above replies). We are fine with both but it is important you understand the implications.

2025-01-05 15:25 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +    function retrieveFunds() external onlyOwner {
Owner should be able to retrieve funds that were reserved for all maximum amount of reviews - but since some of them will not be correct - owner should be able to get the money back, right ?

2025-01-05 15:28 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +    function createSubmission(
But if the reviewer protocol is used for validating then there is no reward for validator on worker unit contract, right? There is only reward for reviewers on Review contract ?

From our understanding and previous discussion, reviewers are paid with funds transferred when creating the Review contract.

2025-01-06 17:02 UTC, lorentsinani requested changes

2025-01-06 17:02 UTC, lorentsinani commented on src/reviewer-protocol/interface/IThriveReview.sol
> +        uint256 acceptedReviewsCount;
I would suggest also to add the comments in line with variables and not new lines so we keep the format of other contracts also.

2025-01-06 17:02 UTC, lorentsinani commented on test/ThriveWorkerUnit.t.sol
>          );
I would check and discard the changes made to other contracts if they are not changes in logic or anything. Keep an eye on formatting also.

2025-01-06 18:35 UTC, vigan-abd commented on src/interface/IThriveWorkerUnitFactory.sol
> +interface IThriveWorkerUnitFactory {
Sorry I'm not fully understanding, were are we importing entire factories? Afaik factory contract would be deployed just once and then used to deploy worker units

2025-01-06 18:36 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +        require(submissionCounter < reviewConfiguration.maximumSubmissions, "Maximum amount of submissions has been reached");
thanks for clarification

2025-01-06 18:37 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +    ) external onlyUserWithBadges(reviewConfiguration.submitterBadges) returns (uint256 submissionId) {
I think since contribution is part of worker unit better to manage just this one there and reuse calls to contract from here

2025-01-06 18:38 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +    function createSubmission(
oh ok then makes sense, much simpler that way, seems we definitely need to comment contracts :sweat_smile:

2025-01-06 18:42 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +                submission.decision = Decision.REJECTED;
Ok I see, good point. But there's the part in requirements where we specified that contract locks funds of user which would be used in case of rejection for paying reviewers, see https://thrivecoin.atlassian.net/wiki/spaces/Product/pages/371261864/Smart+Contract+Requirements#:~:text=Contributors%20can%20submit%20their%20completed%20work%20units%20for%20review.%20During%20submission%2C%20the%20system%20verifies%20that%20the%20contributor%20has%20permission%20to%20submit%20based%20on%20the%20associated%20work%20unit%E2%80%99s%20configuration%20and%20reserves%20the%20necessary%20amount%20of%20THRIVE%20for%20reviewer%20payments.

2025-01-06 18:43 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +    }
Thanks for clarifications, in that case this makes sense, wasn't aware of such edge case as well :sweat_smile:

2025-01-06 18:44 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +    function retrieveFunds() external onlyOwner {
Hmm but funds are locked on worker unit, they should be able to take them from there

2025-01-06 18:46 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +    function createSubmission(
As mentioned [here](https://github.com/ThriveCoin/thc-protocol-sol/pull/20#discussion_r1904507728) we have a penalty mechanism for submissions that get rejected. Unit contract simply transfers funds to validator, in this case it would be reviewer contract, then reviewer contract splits the validation reward between reviewers

2025-01-07 10:13 UTC, matejdrazic commented on src/interface/IThriveWorkerUnitFactory.sol
> +interface IThriveWorkerUnitFactory {
We are importing `ThriveWorkerUnitFactory` interface in `ThriveReviewFactory` contract because we use it to create new instances of `WorkerUnit`.

2025-01-07 15:13 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +    ) external onlyUserWithBadges(reviewConfiguration.submitterBadges) returns (uint256 submissionId) {
As discussed with @rilindmehmeti there will be instances where we do not have a work unit, but only a review contract. How would we handle authorization then?

For this reason, I am maybe inclined to keeping it on `Review` contract, what do you think?

2025-01-07 15:29 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +    function _reachDecisionOnSubmission(uint256 submissionId_) internal {
Done.

2025-01-07 15:36 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +                submission.decision = Decision.REJECTED;
@rilindmehmeti tagging Rilind here so he can check these security implications when we distribute funds to reviewers automatically on finalization.

2025-01-07 16:23 UTC, matejdrazic commented on test/ThriveWorkerUnit.t.sol
>          );
Done.

2025-01-07 16:42 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +    function createSubmission(
Ok, but who pays the reviewers who reviewed the submissions that were accepted?

2025-01-07 19:40 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +    function retrieveFunds() external onlyOwner {
Funds for reviewers (validation reward) are currently stored on `Review` contract and I believe it may be better that way - because `Review` contract should be able to stand on its own - without the `WorkerUnit`.

If we move funds around based on if there is a `WorkerUnit` it introduces complexities thus security concerns. Lets say we store reviewer funds on `WorkerUnit` ->
Example: If there is a `WorkerUnit` connected to `Review`, then the funds are stored and managed on `WorkerUnit`, but if there is not a `WorkerUnit` then the funds should be stored on `Review`. Managing these funds based on if there is a `WorkerUnit` is going to be complex on the `Review` contract.

Thats why I advise we store reviewer funds on `Review` contract.

2025-01-07 20:10 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +    function createSubmission(
look here: https://github.com/ThriveCoin/thc-protocol-sol/pull/20#discussion_r1905956719

2025-01-10 15:57 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +    function createSubmission(
Also, penalty mechanism has been added, should work now as expected.

2025-01-13 15:57 UTC, vigan-abd reviewed
generally looks good to me, let's check these comments and I guess then we can move with finalizing unit tests and formatting/documenting

2025-01-13 15:57 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReviewFactory.sol
> +    }
hmm why not leave these as part of createWorkUnitAndReviewContract? Current approach is very restrictive and possibly we'll end up on having multiple factories instead of one

2025-01-13 15:57 UTC, vigan-abd commented on src/reviewer-protocol/ThriveReview.sol
> +                                                + reviewConfiguration.maximumReviewsPerSubmission - submission.reviewCount;
can we double check this please? not sure if this is correct as I see - submission.reviewCount

2025-01-13 16:15 UTC, lorentsinani requested changes
overall lgtm, added some minor comments. Let's test it out and find if anything is missing in the logic :)

2025-01-13 16:15 UTC, lorentsinani commented on src/reviewer-protocol/ThriveReviewFactory.sol
> +        require(msg.value >= reviewConfiguration_.reviewerRewardsTotalAllocation, "ThriveReviewFactory: small reward amount sent");
I would change the error message to:
`ThriveReviewFactory: Insufficient funds to allocate rewards for reviewers`

2025-01-13 16:15 UTC, lorentsinani commented on src/reviewer-protocol/ThriveReviewFactory.sol
> +            "ThriveReviewFactory: small reward amount"
same as above. Please check for the same issue also in other places so I dont repeat the comment.

2025-01-13 16:15 UTC, lorentsinani commented on src/reviewer-protocol/interface/IThriveReview.sol
> +
please when available don't forget to format the documents and also make sure to delete any empty comment anywhere.

2025-01-13 21:34 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReviewFactory.sol
> +    }
would you maybe rather prefer update functions for these variables?

2025-01-13 21:36 UTC, matejdrazic commented on src/reviewer-protocol/ThriveReview.sol
> +                                                + reviewConfiguration.maximumReviewsPerSubmission - submission.reviewCount;
Yes, I believe it is correct because submitter receives funds they reserved for incorrect reviewers (those who accepted his REJECTED review) plus reviews that were not done (e.g. max reviews per submission = 5, review count is 3 or 4 so there are reserved funds that were not used).

2025-01-13 21:39 UTC, matejdrazic commented on src/reviewer-protocol/interface/IThriveReview.sol
> +
can you please remind me on how do you want them formatted? like an example would be great :)

2025-01-14 01:09 UTC, lorentsinani commented on src/reviewer-protocol/interface/IThriveReview.sol
> +
check ThriveWorkerUnit and Bridge they should be a good example to follow so we dont get out of the format. I added this comment due to some empty lines and empty comments I saw.

2025-01-22 22:23 UTC, vigan-abd approved these changes

2025-01-22 22:25 UTC, lorentsinani approved these changes

2025-01-22 22:25 UTC, merged